version: "3.2"

services:
  node:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: /usr/local/wait-for-it.sh mongo:27017 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - webnet
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    restart: always
    networks:
      - webnet
    volumes:
      - ./data:/data/db

networks:
  webnet:
